name: Build

on: [push, pull_request]

jobs:
    make:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: linux-x86_64
                      os: ubuntu-latest
                    - name: macos-arm64
                      os: macos-latest
                      cxxflags: -arch arm64
                    - name: macos-x86_64
                      os: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: make build/test 'CXXFLAGS=${{ matrix.cxxflags }}'
            - name: Test
              if: ${{ !endsWith(matrix.name, '-arm64') }}
              run: make test

    windows:
        name: ${{ matrix.name }}
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: windows-x86
                      arch: x86
                    - name: windows-x86_64
                      arch: x64
        steps:
            - uses: actions/checkout@v2
            - uses: ilammy/msvc-dev-cmd@v1.5.0
              with:
                  arch: ${{ matrix.arch }}
            - name: Build
              run: cl /std:c++14 /W4 /WX /D_CRT_SECURE_NO_WARNINGS tests/main.cpp
            - name: Test
              run: test.exe
            
